### ISSUE TITLE
[Home Screen] Create the UI for home screen

### ISSUE THREAD

**Issue by Rushi-faldu** [amosproj/amos2024ws04-personalized-play#92]
### Purpose

We need to create a user interface where the user can land after signing in and also after the user ends the playtime session.

### User story

* As a user, I want the app to provide a home screen after signing in so that I can start a playtime session.
* As a user, I want the app to provide a home screen so that I can land on it after my playtime session ends.  

### Acceptance criteria

- [x] The home screen will have a welcoming headline on top like: 'Welcome {user name}'
- [x] The user name that is displayed in the headline is taken from the first-time user onboarding.
- [x] Below the headline, there is a big button that has the label 'Wanna play?' and an arrow or 'Start' primary button to it.
- [x] Clicking on the 'Wanna play?' button will start a new playtime session and the details of what happens will be in this ticket: https://github.com/amosproj/amos2024ws04-personalized-play/issues/104
- [x] After the 'Wanna Play' button there is a section in the home screen that displays the last 3 recently saved activities
- [x] The most recently saved activities will have the name of the saved activity and a button 'Replay'
- [x] Clicking on the Replay' button for one of the recently saved activities will restart the saved activity and the details of what happens will be in this ticket: https://github.com/amosproj/amos2024ws04-personalized-play/issues/109
- [x] All screens (not only the Home screen) will have a menu bar on the bottom and the menu bar will have these options:
- [x] Home icon (that takes you to the home screen)
- [x] Bookmark icon (that takes you to all saved activities - See this ticket: https://github.com/amosproj/amos2024ws04-personalized-play/issues/93)
- [x] Profile icon (that takes you to the profile settings - See this ticket: https://github.com/amosproj/amos2024ws04-personalized-play/issues/105)

### Design notes

* Wireframes are [here](https://app.visily.ai/projects/c005caa3-974a-4e5b-be6c-2b00e5b6645b/boards/1382078)

* Design specifics are [here](https://app.visily.ai/projects/c005caa3-974a-4e5b-be6c-2b00e5b6645b/boards/1436412)

---

### Definition of Done (DoD)

- [ ] The feature has been fully implemented, thoroughly tested, and integrated into the app with no critical bugs or performance issues.
- [ ] Manual testing is complete, verifying that the feature meets all acceptance criteria.
- [ ] Big features are documented inside the code, with clear explanations of functionality, usage, and any relevant edge cases.
- [ ] The feature has undergone peer review, with the code approved by at least one other team member to ensure quality and maintainability.
- [ ] The feature branch has been successfully merged into the main branch, and the pull request is closed and the branch is deleted.
- [ ] The feature’s UI/UX has been reviewed to ensure consistency and alignment with design guidelines.

**Comment by saramakishti** [comment]
Please check with @vivekrudani the status of this task and re-assign if needed
